<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="order.createOrder.CreateOrderFromShop_2Products_Login_COD" tests="1" time="154.651" ignored="0" failures="0" timestamp="18 May 2018 16:50:54 GMT" skipped="0" hostname="QCAutomationTest111" errors="1">
  <testcase name="CO003_VerifyInfoWhenOrderFromShop_2Products_Login_COD" time="154.651" classname="order.createOrder.CreateOrderFromShop_2Products_Login_COD">
    <error type="java.lang.IndexOutOfBoundsException" message="Index: 0, Size: 0">
      <![CDATA[java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at automationLibrary.drivers.DriverWeb.reportFail(DriverWeb.java:228)
	at automationLibrary.executions.ExecutionWeb.setTestFail(ExecutionWeb.java:36)
	at automationLibrary.actions.ActionGenWeb.verifyElementExists(ActionGenWeb.java:502)
	at ShoppingFlow.actions.Action.checkOrderDetailInOrderDetailPage(Action.java:1082)
	at order.createOrder.CreateOrderFromShop_2Products_Login_COD.CO003_VerifyInfoWhenOrderFromShop_2Products_Login_COD(CreateOrderFromShop_2Products_Login_COD.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </error>
  </testcase> <!-- CO003_VerifyInfoWhenOrderFromShop_2Products_Login_COD -->
</testsuite> <!-- order.createOrder.CreateOrderFromShop_2Products_Login_COD -->
